version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: circleci/node:14.17

    working_directory: /home/circleci/todo  # Update to the absolute path of your repository

    steps:
      - checkout

      # Install frontend dependencies
      - run:
          name: Install Frontend Dependencies
          command: cd frontend && npm install

      # Install backend dependencies
      - run:
          name: Install Backend Dependencies
          command: cd backend && npm install

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
